### ISSUE TITLE
Please help me solve the error orz

### ISSUE THREAD

**Issue by vani17a** [wufan-tb/yolo_slowfast#10]
AttributeError: 'Detections' object has no attribute 'imgs'

**Comment by David-19940718** [comment]
The same as issue for me!

**Comment by anilkaratopak** [comment]
I had the same problem and it can be solved by changing yolo_preds.imgs to yolo_preds.ims in yolo_slowfast.py (There are two of them: the first one is located at line 62 and the second one is at line 115).

**Comment by wangkang12** [comment]
Hello,you can modify the 'imgs'to 'ims',it will slove the question.

**Comment by inrped** [comment]
Thanks.I will try again.

**Comment by KingH12138** [comment]
I have tried it and succeed.But I wonder why.....

**Comment by wangkang12** [comment]
Congratulations,you will find the 'yolo_preds' include the 'ims' property by the Debug mode,it's not  'imgs'.
you can refer to the below frame,
![1663815772458](https://user-images.githubusercontent.com/24215656/191649803-2219909d-45b3-4230-8894-d8900098728b.png)

**Comment by David-19940718** [comment]
It worked! Thank you so much.---- Replied Message ***@***.***>Date09/21/2022 23:54 ***@***.***> CcJack ***@***.******@***.***>SubjectRe: [wufan-tb/yolo_slowfast] Please help me solve the error orz (Issue #10)
I have tried it and succeed.But I wonder why.....

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/wufan-tb/yolo_slowfast/issues/10#issuecomment-1253904039",
"url": "https://github.com/wufan-tb/yolo_slowfast/issues/10#issuecomment-1253904039",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
